# ==============================
# GLOBAL CONFIGURATION
# ==============================

GRID_WIDTH = 30
GRID_HEIGHT = 30

NUM_ZOMBIES = 12
NUM_OBSTACLES = 15
NUM_SAFE_ZONES = 2
SAFE_ZONE_MIN_DIST_FROM_SPAWN = 15

MAX_STEPS = 300

INITIAL_HEALTH = 3
RANDOM_SEED = 67