# ==============================
# GLOBAL CONFIGURATION
# ==============================

GRID_WIDTH = 20
GRID_HEIGHT = 20

NUM_ZOMBIES = 5
NUM_OBSTACLES = 10

MAX_STEPS = 200

INITIAL_HEALTH = 3

EPISODES = 100
RANDOM_SEED = 67